# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions


name: GitHub Actions for keripy
on:
  release:
    types: [ created ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.12.2
        uses: actions/setup-python@v2
        with:
          python-version: 3.12.2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel

      - name: Build sdist
        run: python setup.py sdist

      - name: Create tarball
        run: tar czf kourier-install-${{ github.event.release.tag_name }}.tar.gz conf/* dist/* scripts/kourier.sh

      - name: Upload to DigitalOcean Spaces
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl-public --delete --follow-symlinks
        env:
          AWS_S3_BUCKET_ENDPOINT: "sfo3.digitaloceanspaces.com" # Update with your region endpoint
          AWS_S3_BUCKET: "sfo3",
          AWS_ACCESS_KEY_ID: ${{ secrets.SPACES_ACCESS_KEYD }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SPACES_SECRET_KEY }}
          AWS_REGION: ${{ secrets.SPACES_REGION }}
          SOURCE_DIR: "dist"
          DEST_DIR: "kourier"

