# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions


name: Publishing builds to Digital Ocean
on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Prepare Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12.2

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel boto3

    - name: Build sdist
      run: python setup.py sdist

    - name: Create tarball
      run: tar czf kourier-install-${{ github.event.release.tag_name }}.tar.gz conf/* dist/* scripts/kourier.sh

    - name: Upload tarball to DigitalOcean
      run: |
        python scripts/upload.py --access-key ${{ secrets.SPACES_ACCESS_KEYD }} --secret-key ${{ secrets.SPACES_SECRET_KEY }} --region ${{ secrets.SPACES_REGION }} --bucket "healthkeri-deployment" --object-key kourier/kourier-install-${{ github.event.release.tag_name }}.tar.gz --file kourier-install-${{ github.event.release.tag_name }}.tar.gz

