# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions


name: Publishing builds to Digital Ocean
on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Prepare Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12.2

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel

    - name: Build sdist
      run: python setup.py sdist

    - name: Create tarball
      run: tar czf kourier-install-${{ github.event.release.tag_name }}.tar.gz conf/* dist/* scripts/kourier.sh

    - name: Set up S3cmd cli tool
      uses: s3-actions/s3cmd@v1.6.1
      with:
        provider: DigitalOcean # default is linode
        region: ${{ secrets.SPACES_REGION }}
        access_key:  ${{ secrets.SPACES_ACCESS_KEYD }}
        secret_key: ${{ secrets.SPACES_SECRET_KEY }}

    - name: Interact with object storage
      run: |
        s3cmd put kourier-install-${{ github.event.release.tag_name }}.tar.gz s3://healthkeri-deployment/kourier/

